---

title: "Background, Data Access, and Data Structure for the  Multi-scale Ultra-high Resolution (MUR) Sea Surface Temperature (SST) Analysis"
authors: "Chelle Gentemann, Aimee Barciauskas, Mike Chin, Edward M Armstrong"
Gentemann and Barciauskas reformatted the JPL MUR SST into Zarr format from netCDF3 for distribution on AWS Public Dataset Program.  Mike Chin is PI of the JPL MUR SST dataset distributed by the NASA Physical Oceanography Distributed Active Archive Center (PO.DAAC).

<style type="text/css">
.table {
    width: 50%;
}
</style>
 
# Outline

1. [Background](#background)
2. [Data Access](#data-access)
3. [Data Types and Structure](#data-types-and-structure)
4. [Vignettes](#vignettes)
5. [Conversion to Flat Format](#conversion-to-flat-format)

# Background

Sea Surface Temperature (SST) has been observed by satellite instruments since September 1981 and is one of the longest satellite-based records of any Earth climate variable. Measurements from the different satellite sensors need to be calibrated with each other in order to produce an SST Climate Data Record (CDR) that is consistent both in space and time. The microwave (MW) sensors typically have coarser resolutions on the order of 25 km compared to infrared (IR) sensors that can resolve down to 1-km scales. The Figure below illustrates differences in SST using various spatial resolutions, with greater detail observed at higher resolutions. On the other hand, IR-based measurements are prone to data-voids due to cloud contamination, which does not affect MW sensors nearly as much.  Combination of these datasets can thus be complementary, contributing to accuracy of the blended SST maps. The objective for creating the Multi-scale Ultra-high Resolution (MUR) SST is to develop a coherent and consistent daily map of SST at the highest spatial (horizontal) resolution possible.

# Data Access

MUR SST data are stored in the cloud on [Amazon Web Services](https://registry.opendata.aws/mur_sst/).

## Access from Amazon Web Services


The MUR SST data are stored in the cloud using [Amazon Web Services (AWS)](https://aws.amazon.com/) object storage service, [S3](https://aws.amazon.com/s3/). AWS also provides access to flexible cloud computing resources in the form of [EC2](https://aws.amazon.com/ec2/) instances. Users may want to considering analyzing Status and Trends data using an AWS EC2 instance because data transfer will be extremely fast between S3 and EC2 compared to downloading the data to a local machine. An additional benefit of using EC2 for analyses is access to instances with more powerful computing resources than a desktop or laptop. Working with the MUR SST data can be extremely memory intensive, due to their high spatial and temporal resolution, so these additional resources can significantly speed up analyses.


# Data Types and Structure

MUR provides global SST data every day at a spatial resolution of 0.01 degrees in longitude-latitude coordinates, roughly at 1 km intervals (Figure above, bottom right). Currently, the dataset spans from June 1, 2002 to present (i.e., roughly the duration covered by the Aqua satellite).
 
Each MUR data file adheres to the international SST data standard known as the GHRSST Data Processing Specification (GDS; see http://www.ghrsst.org) and contains an estimate of SST uncertainty, land-mask flag, and sea ice concentration for each SST value provided, plus the longitude-latitude grid coordinates and time of analysis, along with the analyzed SST values. The analyzed SST value provided by the MUR dataset is an estimate of the "foundation temperature", or the near-surface temperature below the extent of diurnal fluctuation due to surface solar heating.

## Data Types

A Group for High Resolution Sea Surface Temperature (GHRSST) Level 4 sea surface temperature analysis produced as a retrospective dataset (four day latency) and near-real-time dataset (one day latency) at the JPL Physical Oceanography DAAC using wavelets as basis functions in an optimal interpolation approach on a global 0.01 degree grid. The version 4 Multiscale Ultrahigh Resolution (MUR) L4 analysis is based upon nighttime GHRSST L2P skin and subskin SST observations from several instruments including the NASA Advanced Microwave Scanning Radiometer-EOS (AMSR-E), the JAXA Advanced Microwave Scanning Radiometer 2 on GCOM-W1, the Moderate Resolution Imaging Spectroradiometers (MODIS) on the NASA Aqua and Terra platforms, the US Navy microwave WindSat radiometer, the Advanced Very High Resolution Radiometer (AVHRR) on several NOAA satellites, and in situ SST observations from the NOAA iQuam project. The ice concentration data are from the archives at the EUMETSAT Ocean and Sea Ice Satellite Application Facility (OSI SAF) High Latitude Processing Center and are also used for an improved SST parameterization for the high-latitudes. The dataset also contains additional variables for some granules including a SST anomaly derived from a MUR climatology and the temporal distance to the nearest IR measurement for each pixel. This dataset is funded by the NASA MEaSUREs program ( http://earthdata.nasa.gov/our-community/community-data-system-programs/measures-projects ), and created by a team led by Dr. Toshio M. Chin from JPL. It adheres to the GHRSST Data Processing Specification (GDS) version 2 format specifications. Use the file global metadata "history:" attribute to determine if a granule is near-realtime or retrospective.

## Data Structure

Data are grouped into daily global maps.

## Zarr Data

MUR SST data v4.1 are currently provided in Zarr data format, making it easy to open with the python based Xarray software tool.


### Projection

The MUR SST data are in a Cylindrical Lat-Lon projection on a regular 0.011 degree grid using Ellipsoid: WGS 84.  
    
    
#### analysed_sst


This variable represents the global daily foundation sea surface temperature calculated using Multi-Resolution Variational Analysis (MRVA) method for interpolation.  Input data from the following instruments are used including the NASA Advanced Microwave Scanning Radiometer-EOS (AMSR-E), the JAXA Advanced Microwave Scanning Radiometer 2 on GCOM-W1, the Moderate Resolution Imaging Spectroradiometers (MODIS) on the NASA Aqua and Terra platforms, the US Navy microwave WindSat radiometer, the Advanced Very High Resolution Radiometer (AVHRR) on several NOAA satellites, and in situ SST observations from the NOAA iQuam project.


#### analysis_error

This variable is the estimated error standard deviation of analysed_sst.

#### mask

This variable is a sea/land field composite mask.  A mask value of 1=open sea, 2=land, 5=open-lake, 9=open-sea with ice in the grid, 13=open-lake with ice in the grid.  The landmask is from GMT grdlandmask and the sea ice is from NSIDC.

#### sea_ice


This variable is the sea_ice concentration from the EUMETSAT Ocean and Sea Ice Satellite Application Facility (OSI SAF) High Latitude Processing Center.s

## References

Chin, Toshio Michael, Jorge Vazquez-Cuervo, and Edward M. Armstrong; A multi-scale high-resolution analysis of global sea surface temperature; https://doi.org/10.1016/j.rse.2017.07.029

## Citation

To cite use of this dataset: AWS Public Dataset Program.  JPL MUR MEaSUREs Project. 2015. GHRSST Level 4 MUR Global Foundation Sea Surface Temperature Analysis (v4.1). Ver. 4.1. PO.DAAC, CA, USA.  Data accessed at AWS on [YYYY-MM-DD]. https://doi.org/10.5067/GHGMR-4FJ04.

